// <auto-generated />
using System;
using Generic_POS_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Generic_POS_System.Migrations
{
    [DbContext(typeof(PosContext))]
    [Migration("20220513224228_one-to-many-relationship-added")]
    partial class onetomanyrelationshipadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Generic_POS_System.Data.ProductArcade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductsproductId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductsproductId");

                    b.ToTable("ProductArcade");
                });

            modelBuilder.Entity("Generic_POS_System.Data.Products", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("coverPhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("productDiscount")
                        .HasColumnType("decimal(7,2)");

                    b.Property<string>("productName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("productType")
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("totalProducts")
                        .HasColumnType("int");

                    b.Property<decimal>("unitPrice")
                        .HasColumnType("decimal(7,2)");

                    b.HasKey("productId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Generic_POS_System.Data.ProductArcade", b =>
                {
                    b.HasOne("Generic_POS_System.Data.Products", null)
                        .WithMany("productArcade")
                        .HasForeignKey("ProductsproductId");
                });
#pragma warning restore 612, 618
        }
    }
}
